### ISSUE TITLE
Add a continuous integration service

### ISSUE THREAD

**Issue by kaiiyer** [TomorrowSOC/OpenUBA#4]
Adding a continuous integration service like TravisCI or CircleCI can help automate the software builds, tests, and deployments

**Comment by Jovonni** [comment]
was going to implement travis, but want to explore native github actions now. Working on this soon

**Comment by kaiiyer** [comment]
Okay !

**Comment by Jovonni** [comment]
Let’s close this once it’s set up and working

**Comment by Jovonni** [comment]
travis ci is working
