### ISSUE TITLE
URL not found on server

### ISSUE THREAD

**Issue by kaiiyer** [TomorrowSOC/OpenUBA#6]
I renamed the .mypy_cache folder to mypy to successfully run the Makefile. While starting the server it gives out a 404error. The output screenshot are attached below
![Screenshot1](https://user-images.githubusercontent.com/24914913/72266437-59c54d00-3644-11ea-8718-a915e109f547.png)
![Screenshot at 2020-01-13 20-34-41](https://user-images.githubusercontent.com/24914913/72266445-5f229780-3644-11ea-94d2-7f750d422503.png)

**Comment by Jovonni** [comment]
why did you have to rename the .mypy_cache folder to mypy? That doesn't seem necessary. I havent had to do that. It would have been better to post the problem you were having BEFORE you did that step, and we work to fix that. I am not clear as to where you are headed, or what you are working on because the communication is lacking.

**Comment by kaiiyer** [comment]
The make file has mypy folder in it but the repo don't have the folder thus getting error while running makefile.
How about starting a community in gitter for communication ?

**Comment by Jovonni** [comment]
Discord channel: https://discord.gg/7t4qJk
Telegram: https://t.me/tomorrowsoc

**Comment by kaiiyer** [comment]
Let's follow up the discussions there !

**Comment by Jovonni** [comment]
Let’s close it when we fix it just in case other have this issue

**Comment by Jovonni** [comment]
Updated the INSTALL doc to show exactly what to do. This is the purpose of the Makefile, so you don't have to install or run things independently 

please see:[]( https://github.com/TomorrowSOC/OpenUBA/blob/main_dev_branch/docs/INSTALL.md)

will merge soon

**Comment by Jovonni** [comment]
If you get the mypy not found error, it is because you do not have mypy installed as a module:
[mypy installation](https://mypy.readthedocs.io/en/latest/getting_started.html)
